// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function CancelTransaction(arg1:number):Promise<void>;

export function CreateDiscount(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<models.Discount>;

export function CreateMenuItem(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<models.MenuItem>;

export function CreatePackage(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<models.WashPackage>;

export function CreateShift(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Shift>;

export function CreateTransaction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<backend.CartItem>,arg6:any):Promise<models.Transaction>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.User>;

export function DeleteDiscount(arg1:number):Promise<void>;

export function DeleteMenuItem(arg1:number):Promise<void>;

export function DeletePackage(arg1:number):Promise<void>;

export function DeleteShift(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetActiveDiscounts():Promise<Array<models.Discount>>;

export function GetActiveMenuItems():Promise<Array<models.MenuItem>>;

export function GetActivePackages():Promise<Array<models.WashPackage>>;

export function GetCurrentUser():Promise<models.User>;

export function GetDashboardStats(arg1:string,arg2:string):Promise<models.DashboardStats>;

export function GetDiscounts():Promise<Array<models.Discount>>;

export function GetMenuItems():Promise<Array<models.MenuItem>>;

export function GetPackages():Promise<Array<models.WashPackage>>;

export function GetShifts(arg1:string,arg2:string):Promise<Array<models.Shift>>;

export function GetTodayTransactions():Promise<Array<models.Transaction>>;

export function GetTransactions(arg1:string,arg2:string,arg3:string):Promise<Array<models.Transaction>>;

export function GetUsers():Promise<Array<models.User>>;

export function Login(arg1:string,arg2:string):Promise<models.LoginResponse>;

export function Logout():Promise<void>;

export function ResetPassword(arg1:number,arg2:string):Promise<void>;

export function SaveExcelFile(arg1:string,arg2:string):Promise<string>;

export function UpdateDiscount(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:boolean):Promise<models.Discount>;

export function UpdateMenuItem(arg1:number,arg2:string,arg3:number,arg4:string,arg5:string,arg6:number,arg7:boolean):Promise<models.MenuItem>;

export function UpdateMenuStock(arg1:number,arg2:number):Promise<void>;

export function UpdatePackage(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:boolean):Promise<models.WashPackage>;

export function UpdateShift(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<models.Shift>;

export function UpdateTransactionStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<models.User>;
