// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransaction(arg1) {
  return window['go']['backend']['App']['CancelTransaction'](arg1);
}

export function CreateDiscount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['CreateDiscount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateMenuItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateMenuItem'](arg1, arg2, arg3, arg4, arg5);
}

export function CreatePackage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['CreatePackage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateShift(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateShift'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTransaction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['CreateTransaction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteDiscount(arg1) {
  return window['go']['backend']['App']['DeleteDiscount'](arg1);
}

export function DeleteMenuItem(arg1) {
  return window['go']['backend']['App']['DeleteMenuItem'](arg1);
}

export function DeletePackage(arg1) {
  return window['go']['backend']['App']['DeletePackage'](arg1);
}

export function DeleteShift(arg1) {
  return window['go']['backend']['App']['DeleteShift'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['backend']['App']['DeleteUser'](arg1);
}

export function GetActiveDiscounts() {
  return window['go']['backend']['App']['GetActiveDiscounts']();
}

export function GetActiveMenuItems() {
  return window['go']['backend']['App']['GetActiveMenuItems']();
}

export function GetActivePackages() {
  return window['go']['backend']['App']['GetActivePackages']();
}

export function GetCurrentUser() {
  return window['go']['backend']['App']['GetCurrentUser']();
}

export function GetDashboardStats(arg1, arg2) {
  return window['go']['backend']['App']['GetDashboardStats'](arg1, arg2);
}

export function GetDiscounts() {
  return window['go']['backend']['App']['GetDiscounts']();
}

export function GetMenuItems() {
  return window['go']['backend']['App']['GetMenuItems']();
}

export function GetPackages() {
  return window['go']['backend']['App']['GetPackages']();
}

export function GetShifts(arg1, arg2) {
  return window['go']['backend']['App']['GetShifts'](arg1, arg2);
}

export function GetTodayTransactions() {
  return window['go']['backend']['App']['GetTodayTransactions']();
}

export function GetTransactions(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetTransactions'](arg1, arg2, arg3);
}

export function GetUsers() {
  return window['go']['backend']['App']['GetUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function ResetPassword(arg1, arg2) {
  return window['go']['backend']['App']['ResetPassword'](arg1, arg2);
}

export function SaveExcelFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveExcelFile'](arg1, arg2);
}

export function UpdateDiscount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['backend']['App']['UpdateDiscount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateMenuItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend']['App']['UpdateMenuItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateMenuStock(arg1, arg2) {
  return window['go']['backend']['App']['UpdateMenuStock'](arg1, arg2);
}

export function UpdatePackage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['backend']['App']['UpdatePackage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateShift(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['UpdateShift'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTransactionStatus(arg1, arg2) {
  return window['go']['backend']['App']['UpdateTransactionStatus'](arg1, arg2);
}

export function UpdateUser(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateUser'](arg1, arg2, arg3, arg4);
}
